#improved_idh_no_mask
#HRNet18_iDIH256_Attention
MODELS_PATH: "./issam_video/model/"
EXPS_PATH: "./issam_video/exps/"

HFLICKR_PATH: "./issam_video/IH/IHD/HFlickr"
HDAY2NIGHT_PATH: "./issam_video/IH/IHD/Hday2night"
HCOCO_PATH: "./issam_video/IH/IHD/HCOCO"
HADOBE5K_PATH: "./issam_video/IH/IHD/HAdobe5k"
HADOBE5K_1024_PATH: "./issam_video/IH/IHD/HAdobe5k_1024"

IMAGENET_PRETRAINED_MODELS:
  HRNETV2_W18_SMALL: ""
  HRNETV2_W18: ""
  HRNETV2_W32: ""
  HRNETV2_W40: ""
  HRNETV2_W48: ""
  # HRNETV2_W18_SMALL: "/media/sda/PretrainedModels/hrnet/hrnet_w18_small_model_v2.pth"
  # HRNETV2_W18: "/media/sda/PretrainedModels/hrnet/hrnetv2_w18_imagenet_pretrained.pth"
  # HRNETV2_W32: "/media/sda/PretrainedModels/hrnet/hrnetv2_w32_imagenet_pretrained.pth"
  # HRNETV2_W40: "/media/sda/PretrainedModels/hrnet/hrnetv2_w40_imagenet_pretrained.pth"
  # HRNETV2_W48: "/media/sda/PretrainedModels/hrnet/hrnetv2_w48_imagenet_pretrained.pth"